type District = {
  kodeKabupaten: string;
  namaKabupaten: string;
  namaDistrik: string;
};

export const districts: District[] = [
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak Barat" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak Tengah" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak Timur" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak Timur Tengah" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Fakfak Timur Jauh" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Karas" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Kokas" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Kramongmongga" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Pariwari" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Teluk Patipi" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Tomage" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Wartutin" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Arguni" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Arguni Atas" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Bomberay" },
  { kodeKabupaten: "01", namaKabupaten: "FAKFAK", namaDistrik: "Mbahamdandara" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Kaimana" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Buruway" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Kambrauw" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Teluk Arguni" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Teluk Arguni Atas" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Teluk Etna" },
  { kodeKabupaten: "02", namaKabupaten: "KAIMANA", namaDistrik: "Yamor" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Rasiei" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Naikere" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wamesa" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Kuri Wamesa" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Selatan" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Barat" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Timur" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Utara" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Tengah" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Kota" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Selatan Timur" },
  { kodeKabupaten: "03", namaKabupaten: "TELUK WONDAMA", namaDistrik: "Wasior Selatan Barat" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Bintuni" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Manimeri" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Tuhiba" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Tomu" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Aranday" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Aroba" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Kamundan" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Kaitaro" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Sumuri" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Moskona Selatan" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Moskona Barat" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Moskona Utara" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Moskona Timur" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Meyado" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Merdey" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Babo" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Weriagar" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Kuri" },
  { kodeKabupaten: "04", namaKabupaten: "TELUK BINTUNI", namaDistrik: "Tembuni" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Manokwari Barat" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Manokwari Timur" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Manokwari Selatan" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Manokwari Utara" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Sidey" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Masni" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Prafi" },
  { kodeKabupaten: "05", namaKabupaten: "MANOKWARI", namaDistrik: "Warmare" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Ransiki" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Oransbari" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Tahota" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Neney" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Momi Waren" },
  { kodeKabupaten: "11", namaKabupaten: "MANOKWARI SELATAN", namaDistrik: "Dataran Isim" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Anggi" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Anggi Gida" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Didohu" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Hingk" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Membey" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Sururey" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Taige" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Catubouw" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Testega" },
  { kodeKabupaten: "12", namaKabupaten: "PEGUNUNGAN ARFAK", namaDistrik: "Minyambouw" },
];
